export const actionTypes: {
  UPDATE_VIEW: Symbol;
  SELECT_STORE: Symbol;
  UPDATE_CURRENT_POSITION: Symbol;
} = {
  UPDATE_VIEW: Symbol('UPDATE_VIEW'),
  SELECT_STORE: Symbol('SELECT_STORE'),
  UPDATE_CURRENT_POSITION: Symbol('UPDATE_CURRENT_POSITION'),
};
