export const actionTypes: {
  UPDATE_VIEW: Symbol;
  SELECT_SHOP: Symbol;
  UNSELECT_SHOP: Symbol;
  SELECT_TARGET_SHOP: Symbol;
  UPDATE_CURRENT_POSITION: Symbol;
  UPDATE_SHEET_MODE: Symbol;
  SEARCH_SHOP: Symbol;
  FILTER_SHOP: Symbol;
} = {
  UPDATE_VIEW: Symbol('UPDATE_VIEW'),
  SELECT_SHOP: Symbol('SELECT_SHOP'),
  UNSELECT_SHOP: Symbol('UNSELECT_SHOP'),
  SELECT_TARGET_SHOP: Symbol('SELECT_TARGET_SHOP'),
  UPDATE_CURRENT_POSITION: Symbol('UPDATE_CURRENT_POSITION'),
  UPDATE_SHEET_MODE: Symbol('UPDATE_SHEET_MODE'),
  SEARCH_SHOP: Symbol('SEARCH_SHOP'),
  FILTER_SHOP: Symbol('FILTER_SHOP'),
};
