export const actionTypes: {
  UPDATE_VIEW: Symbol;
  SELECT_STORE: Symbol;
  UNSELECT_STORE: Symbol;
  SELECT_TARGET_STORE: Symbol;
  UPDATE_CURRENT_POSITION: Symbol;
  UPDATE_SHEET_MODE: Symbol;
  SEARCH_STORE: Symbol;
} = {
  UPDATE_VIEW: Symbol('UPDATE_VIEW'),
  SELECT_STORE: Symbol('SELECT_STORE'),
  UNSELECT_STORE: Symbol('UNSELECT_STORE'),
  SELECT_TARGET_STORE: Symbol('SELECT_TARGET_STORE'),
  UPDATE_CURRENT_POSITION: Symbol('UPDATE_CURRENT_POSITION'),
  UPDATE_SHEET_MODE: Symbol('UPDATE_SHEET_MODE'),
  SEARCH_STORE: Symbol('SEARCH_STORE'),
};
